version: "3"

services:
  smtpd:
    container_name: "smtpd-debug"
    build:
      context: smtpd-debug
  card-app:
    container_name: "card-app"
    build:
      context: .
    environment:
      SIERRA_API_URL_BASE: $SIERRA_API_URL_BASE
      SIERRA_API_KEY: $SIERRA_API_KEY
      SIERRA_API_SECRET: $SIERRA_API_SECRET
      SMTP_HOST: $SMTP_HOST
      SMTP_USER: $SMTP_USER
    ports:
      - '8888:80'
